

#datasource
spring:
  profiles:
    include: test

  thymeleaf:
    cache: false
  datasource:
    name: test_person
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
     # 使用数据源
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liaoyb.domain
  type-handlers-package: com.liaoyb.dao

#logging
logging:
  path: log
  level:
    root: error
    mapper: TRACE
